{% set version = "2.4.8" %}

package:
  name: pyspark
  version: {{ version }}

source:
  # PyPI has had issues recently with timely releases due to size constraints of tarball;
  # Building from source runs into StackOverflow errors in CF CI; --> use upstream binary
  url: https://dist.apache.org/repos/dist/release/spark/spark-{{ version }}/pyspark-{{ version }}.tar.gz
  sha256: 3a19b71b8dc8dd91ebc943604a05e1ab01bce052456d42937035632d852d78dc
  patches:
    - 0001-Disable-symlinks-on-Windows.patch

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pypandoc <1.8
    - pandoc
    - python <3.8
    - pip
    - setuptools
  run:
    - python <3.8
    - numpy >=1.7
    - pandas >=0.19.2
    - pyarrow >=0.8.0
    - py4j ==0.10.7
    - setuptools

test:
  commands:
    - pip check
    - bash -c "compgen -c spark && compgen -c pyspark"  # [not win]
    - where *spark*                                     # [win]
  imports:
    - pyspark
    - pyspark.cloudpickle
    - pyspark.ml
    - pyspark.ml.linalg
    - pyspark.ml.param
    - pyspark.mllib
    - pyspark.mllib.linalg
    - pyspark.mllib.stat
    - pyspark.sql
    - pyspark.streaming
  requires:
    - pip

about:
  home: http://spark.apache.org/
  license: Apache-2.0
  # Not yet available in the pypi release
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Apache Spark
  description: Apache Spark is a fast and general engine for large-scale data processing.

extra:
  recipe-maintainers:
    - parente
    - quasiben
    - dbast
    - mariusvniekerk
