{% set name = "pyspark" %}
{% set version = "2.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fb3b4fe47edb0fb78cecec37e0f2a728590f17ef6a49eae55141a7a374c07c8

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy >=1.7
    - pandas >=0.19.2
    - pip
    - py4j ==0.10.7
    - pyarrow >=0.8.0
    - pypandoc
    - python
    - setuptools
  run:
    - numpy >=1.7
    - pandas >=0.19.2
    - py4j ==0.10.7
    - pyarrow >=0.8.0
    - python

test:
  imports:
    - pyspark
    - pyspark.bin
    - pyspark.data
    - pyspark.examples.src.main.python
    - pyspark.jars
    - pyspark.licenses
    - pyspark.ml
    - pyspark.ml.linalg
    - pyspark.ml.param
    - pyspark.mllib
    - pyspark.mllib.linalg
    - pyspark.mllib.stat
    - pyspark.python.lib
    - pyspark.python.pyspark
    - pyspark.sql
    - pyspark.streaming

about:
  home: http://spark.apache.org/
  license: Apache 2.0
  # Not yet available in the pypi release
  # license_file: LICENSE
  summary: 'Apache Spark'
  description: Apache Spark is a fast and general engine for large-scale data processing.

extra:
  recipe-maintainers:
    - parente
    - ericdill
    - quasiben
    - dbast
