{% set name = "pyspark" %}
{% set version = "2.3.1" %}
{% set hadoop_version = "2.7" %}
{% set sha256 = "e87499e5417a64341cbda25e087632dd9f6ce7ad249dfeba47d9d02a51305fc2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://apache.mirrors.hoobly.com/spark/spark-{{ version }}/spark-{{ version }}-bin-hadoop{{ hadoop_version }}.tgz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: cd python && python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pypandoc
    - setuptools

  run:
    - python
    - numpy >=1.7
    - pandas >=0.13.0
    - py4j 0.10.7

test:
  imports:
    - pyspark
    - pyspark.ml
    - pyspark.ml.linalg
    - pyspark.ml.param
    - pyspark.mllib
    - pyspark.mllib.linalg
    - pyspark.mllib.stat
    - pyspark.sql
    - pyspark.streaming

about:
  home: http://spark.apache.org/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Apache Spark'
  description: Apache Spark is a fast and general engine for large-scale data processing.

extra:
  recipe-maintainers:
    - parente
    - ericdill
    - quasiben
